package com.player.bll;
// Generated May 2, 2012 10:48:38 AM by Hibernate Tools 3.2.1.GA

import com.player.bll.Playlist;
import com.player.bll.Song;
import java.util.*;
import org.hibernate.*;
import org.hibernate.cfg.Configuration;

/**
 * PlaylistSongs generated by hbm2java
 */
public class PlaylistSong implements java.io.Serializable {

    private long id;
    private Song song;
    private long playlistId;
    private SessionFactory sf;
    private Session session;
    private Playlist playlist;

    public PlaylistSong() {
//        sf = new Configuration().configure("database/hibernate.cfg.xml").buildSessionFactory();
//        session = sf.openSession();
    }
    
    public PlaylistSong( Playlist playlist, Song song ) {
      this.playlist = playlist;
      this.song = song;
//        sf = new Configuration().configure("database/hibernate.cfg.xml").buildSessionFactory();
//        session = sf.openSession();
    }
    
    public long getId() {
      return id;
    }
    
    public void setId( long id ) {
      this.id = id;
    }
    
    public Song getSong() {
      return song;
    }

    public void setSong( Song song ) {
      this.song = song;
    }
    
    public Playlist getPlaylist() {
      return playlist;
    }

    public void setPlaylist( Playlist playlist ) {
      this.playlist = playlist;
    }
    
    //    @SuppressWarnings("unchecked")
//    public PlaylistSong(Playlist playlistId) {
//        this.playlistId = playlistId;
//        sf = new Configuration().configure("database/hibernate.cfg.xml").buildSessionFactory();
//        session = sf.openSession();
//
//        Query query = session.createQuery("FROM Playlist WHERE playlist_id = :playlistId");
//        query.setParameter("playlistId", playlistId.getPlaylistId());
//        playlist = query.list();
//
//    }

//    public PlaylistSong(int rowId, int songId, Playlist playlistId) {
//        this.rowId = rowId;
//        this.songId = songId;
//        this.playlistId = playlistId;
//    }

//    public int getRowId() {
//        return this.rowId;
//    }
//
//    public void setRowId(int rowId) {
//        this.rowId = rowId;
//    }
//
//    public int getSongId() {
//        return this.songId;
//    }
//
//    public void setSongId(int songId) {
//        this.songId = songId;
//    }
//
//    public Playlist getPlaylistId() {
//        return this.playlistId;
//    }
//
//    public void setPlaylistId(Playlist playlistId) {
//        this.playlistId = playlistId;
//    }
//
//    public Song get(int i) {
//        return getPlaylist().get(i);
//    }
//
//    public int size() {
//        return getPlaylist().size();
//    }
//    public void addPlaylistSong(PlaylistSong ps){
//        ps.setPlaylistId(playlistId);
//        Transaction tx = session.beginTransaction();
//        session.save(ps);
//        tx.commit();
//        ps.addPlaylistSong(ps);
//    }
//    public void add(Song songToAdd) {
//        getPlaylist().add(songToAdd);
//    }
//
//    public void add(int i, Song songToAdd) {
//        getPlaylist().add(i, songToAdd);
//    }
//
//    public boolean contains(Song songToCheck) {
//        return getPlaylist().contains(songToCheck);
//    }
//
//    public void remove(Song songToRemove) {
//        getPlaylist().remove(songToRemove);
//    }
//
//    public Object[][] getDataVector() {
//        int arraySize = getPlaylist().size();
//        Object[][] objectToReturn = new Object[arraySize][5];
//        for (int i = 0; i < arraySize; i++) {
//            Song song = getPlaylist().get(i);
//            objectToReturn[i] = new Object[]{
//                song.getTitle(),
//                song.getArtist(),
//                String.valueOf(song.getTrackLength()),
//                song.getAlbum(),
//                String.valueOf(song.getTrackNumber())
//            };
//        }
//        return objectToReturn;
//    }
//
//    /**
//     * @return the playlist
//     */
//    public List<Song> getPlaylist() {
//        return Collections.unmodifiableList(playlist);
//    }
//
//    /**
//     * @param playlist the playlist to set
//     */
//    public void setPlaylist(LinkedList<Song> playlist) {
//        this.playlist = playlist;
//    }
}
